name: Release using Dagger

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dagger CLI
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh

      - name: Build and Publish
        run: |
          dagger call -m github.com/chainloop-dev/integration-demo/chainloop-demo/dagger build-and-publish \
          --proj . \
          --chainloop-token env:CHAINLOOP_TOKEN \
          --chainloop-signing-key env:CHAINLOOP_SIGNING_KEY \
          --chainloop-passphrase env:CHAINLOOP_SIGNING_PASSWORD

    env:
      CHAINLOOP_TOKEN: ${{ secrets.CHAINLOOP_ROBOT_ACCOUNT }}
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      CHAINLOOP_SIGNING_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      CHAINLOOP_SIGNING_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
